strictPeerDependencies: false
sideEffectsCache: false
linkWorkspacePackages: true

packages:
  - packages/*
  - tests/*

allowBuilds:
  esbuild: true
  puppeteer: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - "@cyco130/eslint-config"
  - "kill-em-all"
